### ISSUE TITLE
Don't remove registry unless it is assigned

### ISSUE THREAD

**Issue by joebowbeer** [actions/setup-node#118]
Given that: If registry-url is specified then a `@scope:registry=` line will always be added to .npmrc if the registry is npm.pkg.github.com,

I think it's a bug for setup-node to remove the `registry=` line from .npmrc. In theory this line could be configuring a registry that is totally unrelated to GitHub packages.

In short, setup-node should only remove lines it is replacing.

In addition, I think better doc is needed regarding the use of the `https://npm.pkg.github.com/owner` proxy registry. Is setup-node compatible with the proxy registry? Or should an explicitly scoped registry always be used?

**Comment by shawnmclean** [comment]
Looking at this [article](https://github.blog/2019-09-11-proxying-packages-with-github-package-registry-and-other-updates/), I think I'm hitting the same issue here where I need to set the npmrc in that pattern for proxying to npm to work.

**Comment by dmitry-shibanov** [comment]
Hello @joebowbeer. Thank you for your report. The setup-node action supports only scoped registry for GitHub packages. If the scope is not provided the action sets the scope automatically for GitHub package registry. I think the action should remove registry line because the .npmrc file can contain any amount of scoped registries but it's limited by common registries. 
For now the action supports only scoped registry for GitHub packages. Could you please create a feature request to add support for proxy registry ? 
For now I'm going to close the issue. If I'm mistaken could please share the link of the documentation and ping us.

**Comment by joebowbeer** [comment]
Please reopen. This is already a feature request for better documentation.

I think there is some confusion in terminology.

You refer to the following as a common registry?

> https://npm.pkg.github.com/owner proxy registry

The documentation should explain when and how setup-node may remove lines from the .npmrc file.
