### ISSUE TITLE
Node.js Default Version Not LTS

### ISSUE THREAD

**Issue by fishcharlie** [actions/setup-node#140]
https://github.com/actions/setup-node/blob/339aa41a8d72adcf661974ca2a947fa1e144530e/action.yml#L8-L10

Is there a reason that the default version for `node-version` is not the latest LTS version ie. `12.x`? Seems like that would be a more reasonable exception for this workflow.

**Comment by bryanmacfarlane** [comment]
I'll fix this.  Actually, it shouldn't even have a default since the intended behavior was to be able to use without installing node by not supplying a value (thus using node globally installed on machine).  That allows for action still setting up problem matchers etc.

https://github.com/actions/setup-node/blob/master/src/setup-node.ts#L11

Since I can't remove in v1 without affecting existing users, I will bump to 12.x in v1 and the upcoming v2 lineage will fix this by not have a default at all.
