### ISSUE TITLE
2.1.1 missing pre-release tag

### ISSUE THREAD

**Issue by ZebraFlesh** [actions/setup-node#189]
v2.1.1 is not marked as a pre-release. This causes GitHub Dependabot to attempt to upgrade users from 1.4.3 to 2.1.1. Is this intentional? (1.4.3 is still tagged as latest, so I'm guessing not.)

**Comment by xt0rted** [comment]
All of my repos keep getting these updates but I'd rather not update them to pre-releases of actions. I can tell Dependabot to ignore v2 for now but then once this is "stable" I won't get an update to that version.

**Comment by jimrazmus** [comment]
This has occurred with the 2.1.2 tag as well.

**Comment by bazzadp** [comment]
Well that's annoying. Because I choose not to go to the beta v2 and closed the dependabot alert, I missed the fact that v1.4.4 was released. And then every action with v1.4.3 or below started breaking after [GitHub removed `add-path` today](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/). Am sure I'm not the only one. Really wish `setup-node` would use the pre-release tag to avoid this.

**Comment by maxim-lobanov** [comment]
Sorry for confusion, I have marked https://github.com/actions/setup-node/releases/tag/v2.1.1 as pre-release

**Comment by hellomykillers** [comment]
I am going to stay right here mama i don't want to keep making all this
noise
