### ISSUE TITLE
Default/Reccomended Matrix

### ISSUE THREAD

**Issue by wesleytodd** [actions/setup-node#25]
The Node Package Maintenance WG has been working on a set of guidelines for package maintainers.  This includes some testing recommendations for which node versions to test in based on your support goals.  Some progress was being made on getting Travis to support tags like `all`, `lts`, `active`, etc.  It would be great if we could get the default matrix (and other common ones) setup here before most users even get started with it to set a good precedence.

Here is the ongoing conversation for that group: https://github.com/nodejs/package-maintenance/issues/205

If there is anything I can do to help move this forward (like working on a PR) I am happy to do that.  If you just want to have a conversation with the PM WG team and then implement it yourself that would also be great!

**Comment by damccorm** [comment]
Thanks for reaching out! We'd already been tracking work to add some of those aliases elsewhere, added #26 in this repo to track that work.

Because of how our jobs our structured, there's not a way for an action to specify a default matrix, so something like `all` is probably out scope (it would take some pretty comprehensive changes across the system to change that). Basically, the short story there is that matrixes create a job for each output of the cross product, and jobs consist of actions (like this one!). So by the time an action is processed, all matrixing has been done.

With that said, there are definitely things we can be doing to encourage good patterns. Areas that jump out where you could help are:

1) Look at #26 and make sure that the aliases there make sense/are we missing any?
2) We populate a bunch of templates for users who are creating new workflows, that's from https://github.com/actions/starter-workflows. This is probably where most users will start - any pointers and/or prs into there would be really helpful. Right now, we have a generic [node template](https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml) where I'm guessing this could go, as well as an [npm publish](https://github.com/actions/starter-workflows/blob/master/ci/npm-publish.yml) template.
3) Docs in this Readme can also be updated according to guidance.

Lastly, I just want to say that I'm really excited and thankful you reached out! The power of GitHub is the community, and that needs to be true of Actions as well - I can't think of any part of the Open Source community that is more central than y'all!

**Comment by wesleytodd** [comment]
Thanks for the quick reply!  As I don't have access to actions at the moment and have not been able to play with them, I am not aware of how it all works or what it is capable of.  What you are saying makes sense though.

> Because of how our jobs our structured, there's not a way for an action to specify a default matrix

This makes sense, but as a module maintainer I think it would be a nice addition to have a very slim configuration which specifies a default for a project type.  For example, if a node project could do something like:

```
template: nodejs
```

Then it would setup all the basics and a default matrix for me, that would be awesome and simple.  Now this is all me who has never used actions, so maybe I am way off base.  But if not, maybe something like this could be a future feature request :)

> Look at #26 and make sure that the aliases there make sense/are we missing any?

I will make sure the WG team is aware of this and comments.

> Right now, we have a generic node template where I'm guessing this could go

Yes, this would be a great start!  I will take a deeper look into that template and see if I can put together the PR to align with what the WG is reccomending.  I should be able to do that without aliases, but the alias support would be critical in the long run.

> Lastly, I just want to say that I'm really excited and thankful you reached out! The power of GitHub is the community, and that needs to be true of Actions as well - I can't think of any part of the Open Source community that is more central than y'all!

OSS is great for some many reasons.  Keep up all the good work you have been doing for the community, we see it and are thankful!

**Comment by damccorm** [comment]
> `template: nodejs`

Huh I see, that makes sense to me. I think chances are that if we do it, then it's probably going to be out of scope until post-general access (which is November 13 I think), but I'll add that as a request.

> I will take a deeper look into that template and see if I can put together the PR to align with what the WG is reccomending. I should be able to do that without aliases, but the alias support would be critical in the long run.

Awesome, thank you! Alias support should be coming very soon (it shouldn't be very hard to implement given that the distro already has most of those ready to download).

**Comment by bryanmacfarlane** [comment]
templates is a feature high on the actions backlog (outside of this repo)

we're tracking the work for latest etc. in #26 so closing this.

Thanks!
