### ISSUE TITLE
How to specify npm version?

### ISSUE THREAD

**Issue by mfbx9da4** [actions/setup-node#324]
I use node-version 14 and npm version 7. How do I specify the npm version to be used? Note ideally it should be cached between installs

**Comment by jherdman** [comment]
This isn't a "true" fix for your problem, but my work around is to add a step before I install packages that just `npm install -g npm@<DESIRED VERSION>`

**Comment by dmitry-shibanov** [comment]
Hello everyone. Thank you for your responses. If you specified `node-version` input you can update `npm` with the `npm install -g npm@version` command. 
If you do not specify the node-version input, default node version on the images will be used (non from toolcache directory).
 - For macOS default node version is installed via [brew](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/node.sh). If you want to update npm, you can try to use this snippet:
 ```
       - run: |
          majorVersion=$(node -v | cut -d. -f1 | cut -d'v' -f2)
          npm i -g npm --prefix=/usr/local/opt/node@$majorVersion
 ```
 - For ubuntu default node version is installed with [sudo](https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu2004.json#L261), that is why you need to run command with sudo: `sudo npm install -g npm@version`
 - For Windows it should work as expected.
 
 For now I'm closing the issue, because we'd prefer to keep discussions in https://github.com/actions/setup-node/issues/213. If you have any concerns feel free to contact us.
