### ISSUE TITLE
Post Run: Cache upload failed because file read failed with EBADF

### ISSUE THREAD

**Issue by davidwinter** [actions/setup-node#332]
I'm using a self-hosted GitHub Runner, and frequently I receive the following error during the `Post Run actions/setup-node@2`:

```
Post job cleanup.
/Users/davidwinter/actions-runner/_work/_tool/node/16.6.2/x64/bin/npm config get cache
/Users/davidwinter/.npm
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /Users/davidwinter/actions-runner/_work/nimblenote/nimblenote --files-from manifest.txt
Warning: uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/Users/davidwinter/actions-runner/_work/_actions/actions/setup-node/v2/dist/cache-save/index.js:3682
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/Users/davidwinter/actions-runner/_work/_actions/actions/setup-node/v2/dist/cache-save/index.js:3682:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

Sometimes, re-running the job will succeed fine and other times it will fail again. It's making my test run success rates completely unreliable and random.

It is occurring on both a macOS and Linux runner.

I've seen some places about changing `ulimit -n` but would appreciate any insight into that fix if it is known?

**Comment by dmitry-shibanov** [comment]
Hello @davidwinter. Thank you for your report. We've found the similar [issue](https://github.com/actions/cache/pull/596) in actions/cache. I think we'll prepare the similar fix. We'll ping you, when the new version of action is released with the fix.

**Comment by jzy3d** [comment]
I also go this on Ubuntu 20.04 in a post job action and am interested by the fix as well!

```
Post job cleanup.
/usr/bin/tar --posix -z -cf cache.tgz -P -C /home/martin/Dev/jzy3d/ci/actions-runner/_work/jzy3d-api/jzy3d-api --files-from manifest.txt
Warning: Error: uploadChunk (start: 33554432, end: 67108863) failed: Cache service responded with 503
/home/martin/Dev/jzy3d/ci/actions-runner/_work/_actions/actions/setup-java/v2/dist/cleanup/index.js:3822
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/martin/Dev/jzy3d/ci/actions-runner/_work/_actions/actions/setup-java/v2/dist/cleanup/index.js:3822:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Comment by dmitry-shibanov** [comment]
Hello everyone. The similar approach as for [actions/cache](https://github.com/actions/cache/pull/596) was implemented in scope of this [release](https://github.com/actions/setup-node/releases/tag/v2.5.1). For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Comment by jozza3000** [comment]
/I get the same problem on a self hosted Windows 11 runner on random builds, any update on this problem?

C:\WINDOWS\System[3](https://github.com/jozza3000/project/actions/runs/5430879755/jobs/9876887859#step:11:3)2\tar.exe --posix -z -cf cache.tgz --exclude cache.tgz -P -C C:/actions-runner/_work/project/project (https://github.com/jozza3000/project/actions/runs/5430879755/jobs/9876887859#step:11:4)02347361
Warning: Failed to save: uploadChunk (start: 100663296, end: 134217727) failed: Cache service responded with [5](https://github.com/jozza3000/project/actions/runs/5430879755/jobs/9876887859#step:11:5)03
C:\actions-runner\_work\_actions\actions\setup-java\v3\dist\cleanup\index.js:401
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (C:\actions-runner\_work\_actions\actions\setup-java\v3\dist\cleanup\index.js:401:31)
    at ReadStream.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at node:internal/fs/streams:258:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:[6](https://github.com/jozza3000/project/actions/runs/5430879755/jobs/9876887859#step:11:6)60:5)
0s

**Comment by ployt0** [comment]
I just got this error running self hosted (Ubuntu 22.04):

```yaml
      - name: set up JDK 17
        uses: actions/setup-java@v3
```

Here's the log:

```text
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/<<runner-user>>/actions-runner/_work/<<repo-name>>/<<repo-name>> --files-from manifest.txt
Warning: Failed to save: uploadChunk (start: 201326592, end: 234881023) failed: Cache service responded with 503
/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401:31)
    at ReadStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at node:internal/fs/streams:262:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
```

This is the almost-default "Android CI" github action. I changed the JDK to 17 because my project required it.

It worked first time on a github runner, but I wanted to run it self hosted. It failed because of this. I re-ran it after 20 minutes of worrying and it passed.

**Comment by ployt0** [comment]
I just got this error running self hosted (Ubuntu 22.04):

```yaml
      - name: set up JDK 17
        uses: actions/setup-java@v3
```

Here's the log:

```text
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/<<runner-user>>/actions-runner/_work/<<repo-name>>/<<repo-name>> --files-from manifest.txt
Warning: Failed to save: uploadChunk (start: 201326592, end: 234881023) failed: Cache service responded with 503
/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/<<runner-user>>/actions-runner/_work/_actions/actions/setup-java/v3/dist/cleanup/index.js:401:31)
    at ReadStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at node:internal/fs/streams:262:9
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
```

This is the almost-default "Android CI" github action. I changed the JDK to 17 because my project required it.

It worked first time on a github runner, but I wanted to run it self hosted. It failed because of this. I re-ran it after 20 minutes of worrying and it passed.

The 503 tells me github's server was having issues, but I could be wrong.
