### ISSUE TITLE
Document which version of npm is used

### ISSUE THREAD

**Issue by davideicardi** [actions/setup-node#438]
Also in relation to various other issues related to the version of npm (like #247 , #213 , ...) I think it should be useful to add a documentation section with the npm version used (I suppose that depends on the `node_version`?).

I can try to submit a PR but not sure how to retrieve these information...

**Comment by zauni** [comment]
In the Node.js website is a list of all Node.js versions and their bundled npm version: https://nodejs.org/en/download/releases/ Unfortunately it is not the most usable list of alle times :)

So as an overall schema Node.js 16.x has npm version 8.x bundled and in Node.js 14.x you get npm version 6.x.

**Comment by davideicardi** [comment]
I'm aware of that list, but from my understanding it is not the one used by `setup-node` action. For example, from what I can see when configuring Node.js 14 I get NPM 8.x.

**Comment by dmitry-shibanov** [comment]
Hello @davideicardi. Thank you for your report. As I know the action does not update npm version of the Nodejs. Besides, versions from node-versions repository [do not update npm version either](https://github.com/actions/node-versions/blob/main/installers/nix-setup-template.sh). Do you use hosted or self-hosted runners ? Could you please provide public repository to reproduce such behaviour. 

I'm not sure if the documentation needs to be updated because this information is available at https://nodejs.org/en/download/releases/ or https://nodejs.org/dist/index.json.

**Comment by davideicardi** [comment]
@dmitry-shibanov @zauni I have tried again today to retrieve the corresponding npm version for each node version and now it seems to follow the https://nodejs.org/en/download/releases/ matrix. I'm sorry, maybe I had some problem on my workflow. My fault. Thank you for your time.

I will close the issue.
