### ISSUE TITLE
Using Node 18 on the Ubuntu 18.04 image

### ISSUE THREAD

**Issue by AndreyIvanov42** [actions/setup-node#507]
**Description:**
A version of GlibC installed on the Ubuntu-18.04 image is different from than used to compile Node18

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node 18.02

**Repro steps:**
[Azure pipeline](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=17397279&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=73c4289c-110b-5085-4a98-4009fa5cc9c8)

**Expected behavior:**
Node18 can be used with Ubuntu-18.04 image

**Actual behavior:**
Node18 can't be used with Ubuntu-18.04 image right now

**Comment by dmitry-shibanov** [comment]
Hello @AndreyIvanov42. Thank you for your report. We'll take a look at it.

**Comment by vsafonkin** [comment]
Hi @AndreyIvanov42

Node.js 18 is compatible with Linux distributions based on glibc 2.28 or later, for example, Debian 10, RHEL 8, and Ubuntu 20.04

You can find more information in the [release notes](https://github.com/nodejs/node/releases/tag/v18.0.0).

The latest glibc version for Ubuntu 18.04 is 2.27
https://launchpad.net/ubuntu/bionic/+source/glibc

**Comment by AndreyIvanov42** [comment]
@vsafonkin I believe that Glibc v2.28 can be compiled from the source to use in Ubuntu 18. Or are there some difficulties with the implementation of this way?

**Comment by maxim-lobanov** [comment]
@AndreyIvanov42 , Currently, we don't build any tools or libraries from source code on Ubuntu images and we shouldn't start doing it.
Main reasons:
- compiling tools from source code will increase image generation time
- maintenance concerns - building something from source code is always not easy. It will require us supporting the code in future
- breaking changes for existing customers. [glibc](https://www.gnu.org/software/libc/) is pretty critical kernel library on Ubuntu OS. Currently, we use glibc that is built by package owners, officially supported and tested. Obviously, switching it to custom version that we build manually from source code can be breaking change because we won't be able to replicate build process fully (build flags / parameters and etc). And even if it is possible to replicate build process - there is not official support of glibc 2.28 on Ubuntu 18. glibc 2.27 is [latest officially provided version](https://launchpad.net/ubuntu/bionic/+source/glibc) on Ubuntu 18.04. It means that no one actually tested glibc 2.28 with Ubuntu 18.04 and there could be any compatibility problems. Since this library is critical part of Ubuntu OS, any compatibility problems can impact other software installed on image (not only Node.js)
(Previously, we had an experience to build Python and openssl from source code on Linux and we had to drop it because it caused a lot of compatibility problems).

Based on [Node.js 18 release notes](https://github.com/nodejs/node/releases/tag/v18.0.0) they officially dropped support of Ubuntu 18. We shouldn't apply any workarounds on image side to overcome it. We shouldn't not allow users to use unsupported configurations of software and OS.

**Comment by dmitry-shibanov** [comment]
Hello @AndreyIvanov42. For now I'm going to close the issue because as @maxim-lobanov and @vsafonkin described that Node.js 18 does not support ubuntu 18.04 with glibc 2.27 and we're not compiling tools from the source code.
