### ISSUE TITLE
trying to use x32 arch 

### ISSUE THREAD

**Issue by shishodiyas** [actions/setup-node#523]
![image](https://user-images.githubusercontent.com/103168986/174255193-baa43f13-13e5-4d0f-b58d-726a27db2264.png)

**Comment by IvanZosimov** [comment]
Hi, @shishodiyas 👋 ! Thank you for your question! I suggest you check the [documentation for the setup-node action](https://github.com/actions/setup-node/tree/v2#readme) because there you can find all the needed information on how to put inputs properly. In your [case](https://github.com/actions/setup-node/blob/v2/action.yml#L12-L13), instead of `x32` you can use `x86`.

I'm going to close this issue now, If you have any question feel free to ping us! 💌
