### ISSUE TITLE
Keep a public list of which Node Versions are currently available in the Internal Distro

### ISSUE THREAD

**Issue by runspired** [actions/setup-node#586]
**Description:**

`actions/setup-node` will first attempt to install a given node version from an internal distro, which according to this comment will fail if that version is not ["one of the popular versions"](https://github.com/actions/setup-node/blob/c81d8ad96dab0a834a87f7a0300b154386f2e26a/src/installer.ts#L88-L123).

A public list of what versions are included should be made available.

**Justification:**

For performance tuning, users may want to choose a specific Node LTS vs latest if it will result in a faster install for CI. Currently there is no way to know if the install has resolved from the internal distro or resulted in an external download for the version.

**Are you willing to submit a PR?**

Yes, though I don't think this is something a community member *could* PR as this list is internal to Github. The way this action works, it does not consult a list but simply moves on to external if the internal download fails.

**Comment by dmitry-shibanov** [comment]
Hello @runspired. Thank you for your feature request. We have a link in the documentation to node-versions releases. Besides, you can check all available releases [here](https://github.com/actions/node-versions/blob/main/versions-manifest.json). 
The action firstly will check hostedtoolcache directory for preinstalled Nodejs versions. If provided SemVer version does not match the action will fallback to the node-versions repository. If node-versions repository does not have a proper release the action will try to install Nodejs from the official [site](https://nodejs.org/dist/). 

For now I'm going to close the issue because the documentation contains all required links to the node-versions repository. Moreover, we update available versions during the day of its release and providing the list of available versions in the documentation will require the manual update of it when a new version is released.
