### ISSUE TITLE
Use the new granular cache actions

### ISSUE THREAD

**Issue by wmertens** [actions/setup-node#654]
**Description:**

Actions/cache now supports choosing when to save and restore.

See https://github.com/actions/cache/discussions/1020 for a description.

So, setup-node can run the save automatically after packages install.

For that, the install command has to be called by setup-node as well.
It can be passed as an option, it can have a default (`npm ci`), and with corepack support #546 the defaults can be sensible, per package manager type.

So then, most devs will just use this action with flags `cache` and `install` and that's all they need to do.

**Justification:**

- more efficient runs
- less boilerplate to use

**Are you willing to submit a PR?**

Maybe, but not now

**Comment by marko-zivic-93** [comment]
Hello @wmertens 
Thank you for your feature request. We will investigate it and come back you you :)

**Comment by dmitry-shibanov** [comment]
Hello @wmertens. I think it should not be implemented in scope of `actions/setup-node` because according to the [ADR](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals) the cache should the majority of use cases. If you need more flexible solution it is better to use [actions/cache](https://github.com/actions/cache). 

For now I'm going to close the issue.

**Comment by wmertens** [comment]
Hmm, wouldn't this functionality be 95% of use cases? Most of the time, you want your package manager of choice to run the install, and you want this to happen as fast as possible, and so you want caching?

**Comment by dmitry-shibanov** [comment]
The setup-node action saves global cache directory for npm, yarn and pnpm that is why I think it does rely on the place where the cache will be saved. Moreover, the main purpose of the action is to setup Nodejs for images and adding extra logic to execute `npm ci` or `npm i` will be an overload for the action.
