### ISSUE TITLE
slow speed in setup-node step

### ISSUE THREAD

**Issue by eerison** [actions/setup-node#726]
**Description:**
Any idea why some setups are really fast `~5sec` and others `~2min` ?

**Action version:**
v3

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**
npm

**Repro steps:**  
https://github.com/shield-wall/myprofile

**Expected behavior:**
slow: https://github.com/shield-wall/myprofile/actions/runs/4505022388/jobs/7930236281
fast: https://github.com/shield-wall/myprofile/actions/runs/4505022388/jobs/7930228983

**Actual behavior:**
every setup be few seconds 🚀

**Comment by awer000** [comment]
So slow too.

**Comment by Santas** [comment]
We have the same issue. `setup-node` should either cache at least some Node v19 binaries or allow caching of the binary through artifacts/... so it doesn't need to be downloaded from nodejs.org on every run.

**Comment by Tirke** [comment]
We have a lot of issues like that 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/15009522/229554247-69def796-53b3-4abe-8816-7d70ce1b2de9.png">
we added a really slow timeout because it can go up to an hour like that doing nothing.

**Comment by lgaspari** [comment]
> We have a lot of issues like that <img alt="image" width="581" src="https://user-images.githubusercontent.com/15009522/229554247-69def796-53b3-4abe-8816-7d70ce1b2de9.png"> we added a really low timeout because it can go up to an hour like that doing nothing.

Having the same issue here, however in my case it started when I changed from `macos-latest` runner to `self-hosted` in my M1. I can't get to pass the setup step due to timeout. It takes up more than an hour to download and it ends up failing anyway because of my job timeout... I've also tried changing node version without luck (from `16.15.x` to `16.20.x`).

**Comment by dusan-trickovic** [comment]
Hello, everyone! Thank you for pointing out the inconsistencies in setup times on a project basis. Unfortunately, we believe that the problem here can't be very easily fixed...

Given the fact that our hosted toolcache directory and manifest contains only LTS versions (e.g. `16.x`, `18.x`, `20.x`), the action tries and fails to resolve the provided 19.x version by looking into there first. Next, it looks for it in dist (nodejs.org), which does have it, but ultimately can take a varying amount of time that is beyond our control to fetch and set up.

As for the case that @millsp pointed out, where it's version 18 making an issue, we do believe that the problem was also external (and temporary) in nature. That being said, the cache servers might have been temporarily unavailable or a bit overwhelmed with requests which resulted in cache download getting stuck even though the node was installed. Sadly, this was probably more of an infrastructure issue than something we could fix with code...

If you want to learn more about versions (and aliases) in particular, you can check out the README of our repository, more specifically **[supported version syntax](https://github.com/actions/setup-node#supported-version-syntax)** .

If you have any other concerns, feel free to reply or open up a new issue. Alternatively, if we answered your question, please feel free to let us know that also. We appreciate your input! :)

**Comment by Santas** [comment]
It doesn't make sense the binary isn't at least cached at the job level. Our jobs are again crashing today.

**Comment by dusan-trickovic** [comment]
Hi, @Santas ! Thank you for the follow-up. We will take a closer look into the issue and, hopefully, come back to you with a potential solution soon. But first, just to clarify - are you still trying to use Node v19 in your jobs? We appreciate your time and cooperation :)

**Comment by dusan-trickovic** [comment]
Hello @Santas ! Thank you for your patience. I have discussed the issue with my colleagues and, unfortunately, there isn't much that we can do about it at this time. The reason being that it simply isn't an issue on our end - it can take varying amounts of time to fetch and install a Node version that isn't available out of the box in our node-versions repository. As non-LTS versions aren't, that variable definitely applies there.

I will have to close this issue now, as its solution is out of our reach, but if any other problem arises while using our software, please feel free to file a new issue and we will be happy to take a look at it.

Thank you for your time and cooperation! :)
