### ISSUE TITLE
Doesn't save cache if one of the subsequent steps fails

### ISSUE THREAD

**Issue by koistya** [actions/setup-node#798]
**Description:**

After dependencies are successfully installed, it's expected the action to save the cache. But, it doesn't do it if one of the subsequent steps (after `yarn install`, `npm install`) fails.

**Action version:**

`3.7.0`

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

**Repro steps:**  
Configure the action as described in `README`, add `npm install` step followed by some dummy step that fails and observe caching behavior in logs.

**Expected behavior:**

After `npm install` (or, `yarn install` etc.) step succeeded, it's expected the action to preserve the NPM artifacts for future executions regardless if any of the subsequent steps failed or not. 

**Actual behavior:**

Even if `npm install` (or, `yarn install` etc.) step succeeded, the cache is not being saved if one of the subsequent steps failed.

**Comment by dusan-trickovic** [comment]
Hello, @koistya ! Thank you for creating this issue, we will investigate it and see what can be done :)

**Comment by dmitry-shibanov** [comment]
Hello @koistya. Thank you for your report. I think it is impossible to implement right now because we can't determine on which steps the job was failed, so even if the action gets cached paths we can't guarantee that it is valid. 

For now I'm going to close the issue. If you have any concerns feel free to ping us.
