### ISSUE TITLE
v3.7 takes a lot of time on Ubuntu

### ISSUE THREAD

**Issue by HKLab** [actions/setup-node#820]
**Description:**
Whenever I re-run the job it takes a lot of time and all the jobs using setup-node on the same repository get clogged
Wait for a while after canceling all jobs using setup-node and then re-run the job will return to normal
https://github.com/hkmodmanager/ModpackSource/actions/runs/5677545458
https://github.com/hkmodmanager/ModpackSource/actions/runs/5677547870

**Action version:**
v3.7

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

node - 19.x

**Repro steps:**  
Occurs randomly when executing Re-run jobs

**Expected behavior:**
Take time less than 1min

**Actual behavior:**
takes more than 5 minutes

**Comment by dusan-trickovic** [comment]
Hi @HKLab ! Thank you for reporting the issue, we will investigate it and see what can be done :)

**Comment by dusan-trickovic** [comment]
Hello again @HKLab! I'm reaching out to you to ask if there were any developments regarding the issue in the meantime? Perhaps you've tried running it again? I took a look into the runs you provided and it seems to be getting stuck on the Setup Node step, in particular because you're trying to use a version that isn't in our manifest (`19.x`).

This can get tricky, as our action fetches non-LTS versions directly from Node which automatically means introducing more factors into the overall user experience (e.g. if their servers are temporarily unavailable or overly busy with traffic, it can take more time to fetch your version). However, even if that does happen, we've seen experiences where simply re-running the workflow some seconds later solves the issue.

With that said, I would like to ask you if you've tried running your workflows again after the runs you've included (and with the same versions)? Have you tried running our action with just `actions/setup-node@v3` instead of `v3.7.0` or, perhaps, with one of the LTS versions of Node like 16, 18, or 20?

Thank you for your cooperation :)

**Comment by thecodeassassin** [comment]
This is a real issue.

      - uses: actions/setup-node@v3
        with:
          node-version: 17
          registry-url: 'https://npm.pkg.github.com'


Took 10+ minutes just for this step

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 17
          registry-url: 'https://npm.pkg.github.com'
          
Downgrading to 3.6.0 and it was done in 4 seconds

**Comment by dusan-trickovic** [comment]
Hello @thecodeassassin ! Thanks for the input, we will investigate the potential cause behind it. However, after additional testing on my side, `v3.7.0` seemed to be performing well for me (the total waiting time was in seconds rather than minutes). There is still a chance that the official server was busy at the time, as your requested version was 17 (which is also not in our manifest). It has happened with some similar reported issues in the past.

However, just to be on the safe side, we will investigate the `3.7` in any case and see if anything can be done on our end to tackle this problem. If anything changes (or you decide to try again with the same versions of the action and Node or otherwise and get a different result), please feel free to leave an update here.

Thank you for your time :)
