### ISSUE TITLE
Installing Node@19.6.0 fails continuously for unknown reasons.

### ISSUE THREAD

**Issue by oliversalzburg** [actions/setup-node#838]
**Description:**
When I try to install 19.6.0, the pipeline hangs on the `setup-node` step for 25 minutes and then fails.

**Action version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

Node: 19.6.0

**Repro steps:**  
I wish I knew. I hope it's not just the NodeJS version that is causing this.

**Expected behavior:**
Node is installed.

**Actual behavior:**
```
Attempting to download 19.6.0...
Not found in manifest. Falling back to download directly from Node
Acquiring 19.6.0 - x64 from https://nodejs.org/dist/v19.6.0/node-v19.6.0-linux-x64.tar.gz
aborted
Waiting 13 seconds before trying again
aborted
Waiting 16 seconds before trying again
Error: aborted
```
The URL works just fine for me.

**Comment by oliversalzburg** [comment]
After many retries it finally completed, after 30m runtime for the step. I have no idea what's going on.
![image](https://github.com/actions/setup-node/assets/1658949/2737e243-3a44-41f9-be6c-2de9cfe9fe10)

**Comment by selarun13** [comment]
0x6F99E90Dd385c23826b416528e325214671FeBf6

**Comment by dusan-trickovic** [comment]
Hello, @oliversalzburg! Thank you for reporting the issue, we will take a closer look into it and see what can be done :)

**Comment by oliversalzburg** [comment]
I'm sure there is nothing really wrong with this specific version, and I've seen other issues that report problems with non-LTS versions. Maybe some good workaround could be suggested for this. Or maybe some troubleshooting mode to at least be able to see the response headers from `nodejs.org`.

**Comment by dusan-trickovic** [comment]
@oliversalzburg ! Thank you for pointing that out. Based on the version you were trying to install, given that it's a non-LTS one, there's a high chance that this issue isn't on our side to begin with. Those get fetched directly from `nodejs.org` and, therefore, their availability pretty much completely depends on outside factors (most likely the availability of their servers at that time).

Have you tried setting it up and running the workflow again since the last time? Were there any changes? Maybe even used self-hosted runners (you can find out more about them in our [docs](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners))? They provide some more flexibility in terms of hardware and OS and could, possibly, help you cut down the time it takes for your selected version to be downloaded (you would likely just need to install it locally first).

In any case, I will discuss your troubleshooting mode suggestion with the team and see what can be done on that front. For more verbose outputs and information, though, you could also [enable debugging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) on your repo and see if that provides a better insight into the processes happening at the step level.

Thank you very much for your cooperation! :)

**Comment by oliversalzburg** [comment]
@dusan-trickovic I completely accept that this is an upstream issue. I felt like maybe too many GitHub hosted runners try to pull NodeJS versions from their server and they might just try to limit their traffic. I can relate to that.

We have since been able to get the pipeline running after many retries. Given that we only needed this version a few times to zero in on an issue, it's no longer blocking us.

We're looking into self-hosted runners for other reasons, but I'm sure this would help.

I guess, this is a documentation issue at best. I'm not sure if this makes any sense, but could there be a mode of operation where you can drop the `.tar.xz` NodeJS package into the repo and have `setup-node` install it?

**Comment by justvanrossum** [comment]
FWIW, I'm currently also experiencing this issue, `actions/setup-node@v3`, `node-version: [19.x]`

**Comment by phuwin95** [comment]
Same here with 
```
Run actions/setup-node@v1
  with:
    node-version: 18.17.0
    registry-url: https://npm.pkg.github.com/
    always-auth: false
```

**Comment by viniciuspalma** [comment]
Problem continues, github action gets stuck for about 30min. Can at least it has a backoff policy and stop the retrying. This costs 💵 💵

**Comment by aparnajyothi-y** [comment]
Hello, Thank you for reaching out. We currently support only LTS versions of Node.js from the node-versions repository. The issue you're encountering seems to be an upstream problem, likely due to traffic limitations on the Node.js servers.

Regarding your suggestion about dropping the .tar.xz Node.js package into the repository, we may consider it for future enhancements. However, at the moment, this action doesn't support manually uploaded Node.js packages.

We appreciate your feedback and will keep it in mind for future improvements. Please feel free to reach out if you need further assistance.

**Comment by oliversalzburg** [comment]
Good enough. Thanks 🙂

**Comment by aparnajyothi-y** [comment]
Hello @oliversalzburg, Thank you for the confirmation hence we are proceeding to close this issue.
Please feel free to reach us in case of further clarifications/ concerns to reopen this issue.
