### ISSUE TITLE
node-versions only packaging x64, include arm64 please

### ISSUE THREAD

**Issue by jpike88** [actions/setup-node#857]
I have arm runners and use an LTS version of node included in https://github.com/actions/node-versions/releases. But I use arm64, only x64 builds are in there.

Please include both architectures so I can leverage fast downloads.

Thanks

**Comment by nikolai-laevskii** [comment]
Thanks for creating an issue! We will look into and come back to you with the details!

**Comment by bennet-esyoil** [comment]
Currently experiencing this:

```
Attempting to download 18...
Not found in manifest. Falling back to download directly from Node
Acquiring 18.18.0 - arm64 from https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-arm64.tar.gz
aborted
Waiting 18 seconds before trying again
```

could be resolved by including arm versions directly?

**Comment by jpike88** [comment]
Much appreciated. As you can see it's a very annoying wait!

<img width="744" alt="Screenshot 2023-09-22 at 14 59 12" src="https://github.com/actions/setup-node/assets/9585787/82c02b90-9c85-40a9-8725-4fccfc0ad576">

**Comment by jpike88** [comment]
this issue is quite acute. is there an official workaround for this (maybe I can cache the binary myself), while still leveraging this step?

**Comment by dustin-engstrom** [comment]
I think we have to wait for this issue to be addressed.

https://github.com/actions/runner-images/issues/5631

**Comment by jpike88** [comment]
Why wait for that?? Buildjet has offered arm64 runners for quite some time now, it’s those runners that I’m using. Not sure why waiting for github to catch up is necessary here.

**Comment by dustin-engstrom** [comment]
> Why wait for that?? Buildjet has offered arm64 runners for quite some time now, it’s those runners that I’m using. Not sure why waiting for github to catch up is necessary here.

My comment is based on the way this `setup-node` action currently works. If you look [here](https://github.com/actions/setup-node/blob/2a017f350dbf6c4b6bb4508cc83809719115162e/src/distributions/official_builds/official_builds.ts#L147) you'll see that it pulls a manifest file of current node-versions from [this file in a separate repo](https://github.com/actions/node-versions/blob/main/versions-manifest.json). But that file does not currently contain any arm64 targets; which is why the action always ends up downloading directly from Node instead. The issue I linked in my comment is a request to add arm64 targets to that manifest file in the other repo.

Feel free to propose other workarounds though. I just thought it would be helpful to know that there's an issue raised already at the source of this problem.

**Comment by aparnajyothi-y** [comment]
fix merged and arm64 packages supporting for linux and windows.
